### ISSUE TITLE
What version of pytorch_lightning are you using?And  a RuntimeError occured.

### ISSUE THREAD

**Issue by adgai1** [LUMIA-Group/Leveraging-Self-Supervised-Learning-for-AVSR#4]
2022-08-15 22:05:39 | INFO | pytorch_lightning.utilities.seed | Global seed set to 19260817
[W ..\aten\src\ATen\Context.cpp:70] Warning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (function operator ())
2022-08-15 22:05:53 | INFO | pytorch_lightning.utilities.rank_zero | GPU available: True, used: True
2022-08-15 22:05:53 | INFO | pytorch_lightning.utilities.rank_zero | TPU available: False, using: 0 TPU cores
2022-08-15 22:05:53 | INFO | pytorch_lightning.utilities.rank_zero | IPU available: False, using: 0 IPUs
2022-08-15 22:05:53 | INFO | pytorch_lightning.utilities.rank_zero | HPU available: False, using: 0 HPUs
D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:155: LightningDeprecationWarning: The `LightningModule.get_progress_bar_dict` method was deprecated in v1.5 and will be removed in v1.7. Please use the `ProgressBarBase.get_metrics` instead.
  "The `LightningModule.get_progress_bar_dict` method was deprecated in v1.5 and will be removed in v1.7."
D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:386: LightningDeprecationWarning: The `Callback.on_epoch_start` hook was deprecated in v1.6 and will be removed in v1.8. Please use `Callback.on_<train/validation/test>_epoch_start` instead.
  f"The `Callback.{hook}` hook was deprecated in v1.6 and"
2022-08-15 22:06:04 | INFO | pytorch_lightning.accelerators.gpu | LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2022-08-15 22:06:04 | INFO | pytorch_lightning.callbacks.model_summary | 
  | Name                      | Type               | Params
-----------------------------------------------------------------
0 | maskedLayerNorm           | MaskedLayerNorm    | 0     
1 | EncoderPositionalEncoding | PositionalEncoding | 0     
2 | wav2vecModel              | Wav2Vec2Model      | 315 M 
3 | audioConv                 | conv1dLayers       | 1.3 M 
4 | audioEncoder              | TransformerEncoder | 18.9 M
5 | jointOutputConv           | outputConv         | 470 K 
6 | decoderPositionalEncoding | PositionalEncoding | 0     
7 | embed                     | Sequential         | 20.5 K
8 | jointAttentionDecoder     | TransformerDecoder | 25.2 M
9 | jointAttentionOutputConv  | outputConv         | 472 K 
-----------------------------------------------------------------
361 M     Trainable params
0         Non-trainable params
361 M     Total params
1,447.410 Total estimated model params size (MB)
Sanity Checking DataLoader 0:  50%|█████     | 1/2 [00:05<00:05,  5.97s/it]D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\utilities\data.py:73: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  "Trying to infer the `batch_size` from an ambiguous collection. The batch size we"
Epoch 0:   0%|          | 0/4367 [00:00<?, ?it/s] Traceback (most recent call last):
  File "D:/Leveraging-Self-Supervised-Learning-for-AVSR-main/train.py", line 495, in <module>
    main()
  File "D:/Leveraging-Self-Supervised-Learning-for-AVSR-main/train.py", line 490, in main
    trainer.fit(model, LRS2Dataloader)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 771, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1236, in _run
    results = self._run_stage()
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 207, in advance
    self.optimizer_idx,
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 378, in _optimizer_step
    using_lbfgs=is_lbfgs,
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\core\lightning.py", line 1646, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\core\optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\torch\optim\optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\torch\optim\adam.py", line 66, in step
    loss = closure()
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 140, in _wrap_closure
    closure_result = closure()
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 143, in closure
    self._backward_fn(step_output.closure_loss)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 311, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 168, in backward
    self.precision_plugin.backward(self.lightning_module, closure_loss, *args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 80, in backward
    model.backward(closure_loss, optimizer, *args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\pytorch_lightning\core\lightning.py", line 1391, in backward
    loss.backward(*args, **kwargs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\torch\tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\Anaconda\envs\pyfairseq\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: ctc_loss_backward_gpu does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

**Comment by yan159yan** [comment]
i got the same error with pytorch-lightning==1.6.5 ，
and i fix this error by adding "torch.use_deterministic_algorithms(False)" before  calculate the ctcloss in Line 345 and Line 379

**Comment by xichenpan** [comment]
Hi, sorry for the delayed reply, you can email me if I do not answer your question in time.

Our pytorch lightning version is < 1.5.0, this lib changed so fast these days. you could try to set deterministic=False here.
https://github.com/LUMIA-Group/Leveraging-Self-Supervised-Learning-for-AVSR/blob/main/train.py#L476
